### ISSUE TITLE
login page header text is different

### ISSUE THREAD

**Issue by nnnolan** [NatFletch/FBLA-Programming-2023#6]
@NatFletch 
<img width="1702" alt="Screen Shot 2023-03-08 at 2 21 49 PM" src="https://user-images.githubusercontent.com/89788103/223841068-ed5a1276-9578-4333-a01b-20a81e158733.png">
^^^ login page

<img width="1702" alt="Screen Shot 2023-03-08 at 2 21 49 PM" src="https://user-images.githubusercontent.com/89788103/223841237-b7749f28-5829-4b2b-ab67-d9f2e95230f6.png">
^^^every other page

so i believe this is because i'm using a different font in my css on the profile page, should we forgot that or should we change the header text to be consistent throughout?

**Comment by nnnolan** [comment]
<img width="1728" alt="Screen Shot 2023-03-08 at 2 22 35 PM" src="https://user-images.githubusercontent.com/89788103/223841456-e9b648f3-d61f-4879-856b-9dce0ab406dc.png">
^^^ this is every other page my bad

**Comment by nnnolan** [comment]
shit idek

**Comment by nnnolan** [comment]
@NatFletch i commented out the font on https://github.com/NatFletch/FBLA-Programming-2023/commit/f1071477ac23d841e15bbebeb6932aa23cbdf09e , we can discuss changing the font later but for now its not that big of a deal

**Comment by NatFletch** [comment]
I just left it as the default bootstrap font cuz I think it looks alright. If you want to change it you can but be sure to change it for the rest of the pages
