### ISSUE TITLE
make title consistent 

### ISSUE THREAD

**Issue by nnnolan** [NatFletch/FBLA-Programming-2023#7]
The Home Page's <title> attribute is "Smithville Attendance"

The Profile, Login, & Register title's are  "Log In"

Leaderboard & Store are "FBLA 2023"

i don't really know how important this is, it probably isnt, but still prob something we should do for coherency. this is your call on what the naming is @NatFletch

**Comment by NatFletch** [comment]
Pretty sure the title tag affects the window title if im not mistaken. That is something i need to be changed. I forgot to change the titles cuz all of those pages are just templates

**Comment by nnnolan** [comment]
yeah naturally, just something to handle

**Comment by nnnolan** [comment]
html moment tbh

**Comment by nnnolan** [comment]
and it does affect the window title, mb shouldve elaborated

**Comment by NatFletch** [comment]
This was fixed
